apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.project.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.project.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.project.name }}
    spec:
      containers:
        - name: {{ .Values.project.name }}
          image: {{ .Values.project.image }}
          envFrom:
            - secretRef:
              name: msteste-secrets
          resources:
            requests:
              memory: {{ .Values.project.resources.requests.memory }}
              cpu: {{ .Values.project.resources.requests.cpu }}
            limits:
              memory: {{ .Values.project.resources.limits.memory }}
              cpu: {{ .Values.project.resources.limits.cpu }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlogcontainers
              mountPath: /var/log/containers
            - name: dockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
        - name: fluent-bit
          image: fluent/fluent-bit:2.1
          args: ["-c", "/fluent-bit/etc/fluent-bit.conf"]
          resources:
            requests:
              memory: {{ .Values.fluentBit.resources.requests.memory }}
              cpu: {{ .Values.fluentBit.resources.requests.cpu }}
            limits:
              memory: {{ .Values.fluentBit.resources.limits.memory }}
              cpu: {{ .Values.fluentBit.resources.limits.cpu }}
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlogcontainers
              mountPath: /var/log/containers
            - name: dockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: config
              mountPath: /fluent-bit/etc
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: dockercontainers
          hostPath:
            path: /var/lib/docker/container
        - name: config
          configMap:
            name: fluent-bit-config-{{ .Values.project.name }}