apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.project.name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.project.name }}.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.project.name }}
            port:
              number: 8080
