apiVersion: v1
kind: Secret
metadata:
  name: msteste-secrets
type: Opaque
data:
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.username | b64enc }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.password | b64enc }}
  RABBITMQ_VIRTUAL_HOST: {{ .Values.rabbitmq.vhost }}
