apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.project.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.project.name }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080