server:
  port: 8080

app:
  locale: "pt_BR"
  integrations:
    messaging:
      provider: "rabbitmq"
  
spring:
  application:
    name: "@project.name@"
    version: "@project.version@"

# Basic connection
SPRING_RABBITMQ_HOST: rabbitmq.rabbitmq.svc.cluster.local
SPRING_RABBITMQ_PORT: 32601
SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
# Connection settings
SPRING_RABBITMQ_VIRTUAL_HOST: ${RABBITMQ_VIRTUAL_HOST}
SPRING_RABBITMQ_CONNECTION_TIMEOUT: 5s
# Default exchange for the application
APP_MESSAGING_EXCHANGE_NAME: iubi-platform-exchange
APP_MESSAGING_EXCHANGE_TYPE: topic
APP_MESSAGING_EXCHANGE_DURABLE: true
# RoutingKey
SOURCE_ROUTING_KEY: notification-service
DESTINATION_ROUTING_KEY: notification-service


springdoc:
 swagger-ui:
   path: "/swagger-ui.html"

logging:
  config: "classpath:log4j2.xml"
  level:
    root: "INFO"
    org:
      springframework:
        web: "INFO"
