#######################
# Project msteste

project:
  name: msteste
  image: ""
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "1024Mi"
      cpu: "300m"

namespace: iubi

deployment:
  replicas: 1

#######################
# Fluent Bit

fluentBit:
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "1024Mi"
      cpu: "300m"
  timeFormat: "%Y-%m-%dT%H:%M:%S"
  log:
    level: info

rabbitmq:
  username: ""
  password: ""
  vhost: ""